server:
  port: 8181


spring:
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: public
    h2:
      console:
        enabled: true
        path: /h2
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: public

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE